/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmViewChild.java
 *
 * Created on Sep 5, 2010, 8:16:14 AM
 */

package GUI;

import BL.NannyBL;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class frmViewChild extends javax.swing.JDialog {

    private int ChildCode;
    private NannyBL nannybl;
    private ResultSet rs;
    /** Creates new form frmViewChild */
    public frmViewChild(java.awt.Frame parent, boolean modal, int Code) {
        super(parent, modal);
        ChildCode = Code;
        initComponents();
        setText();
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((ds.width - this.getWidth()) / 2, (ds.height - this.getHeight()) / 2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plTable = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbFName = new javax.swing.JLabel();
        lbAgeGroup = new javax.swing.JLabel();
        lbAddress = new javax.swing.JLabel();
        lbBirthday = new javax.swing.JLabel();
        lbSex = new javax.swing.JLabel();
        lbLName = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbPName = new javax.swing.JLabel();
        lbPWorkNumber = new javax.swing.JLabel();
        lbPPhone = new javax.swing.JLabel();
        lbPEmail = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        lbNextOfKinContact = new javax.swing.JLabel();
        lbNoteAboutChild = new javax.swing.JLabel();
        lbRegistrationDate = new javax.swing.JLabel();
        lbDateReceived = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lbCurrentMedication = new javax.swing.JLabel();
        lbPasIllness = new javax.swing.JLabel();
        lbDocterName = new javax.swing.JLabel();
        btClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View Children - Child Care");

        plTable.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "View detail of Children", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 17))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Child"));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel5.setText("Last Name :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel7.setText("Sex :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel8.setText("Birthday :");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel20.setText("Address :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel1.setText("Age Group :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel6.setText("First Name :");

        lbFName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbFName.setForeground(new java.awt.Color(51, 0, 0));

        lbAgeGroup.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbAgeGroup.setForeground(new java.awt.Color(51, 0, 0));

        lbAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbAddress.setForeground(new java.awt.Color(51, 0, 0));

        lbBirthday.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbBirthday.setForeground(new java.awt.Color(51, 0, 0));

        lbSex.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbSex.setForeground(new java.awt.Color(51, 0, 0));

        lbLName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbLName.setForeground(new java.awt.Color(51, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbBirthday)
                            .addComponent(lbAddress)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbAgeGroup)
                            .addComponent(lbSex)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lbLName))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(lbFName)))
                .addContainerGap(268, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbFName))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbLName))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbSex))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbAgeGroup))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(lbAddress))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbBirthday))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Parent"));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel12.setText("Parent Name :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel13.setText("Parent Work Number :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel14.setText("Parent Mobile Number :");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel15.setText("Parent Email Address :");

        lbPName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbPName.setForeground(new java.awt.Color(51, 0, 0));

        lbPWorkNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbPWorkNumber.setForeground(new java.awt.Color(51, 0, 0));

        lbPPhone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbPPhone.setForeground(new java.awt.Color(51, 0, 0));

        lbPEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbPEmail.setForeground(new java.awt.Color(51, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPName)
                    .addComponent(lbPWorkNumber)
                    .addComponent(lbPPhone)
                    .addComponent(lbPEmail))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lbPName))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPWorkNumber)
                    .addComponent(jLabel13))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lbPPhone))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lbPEmail))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Other information"));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel32.setText("Next Of Kin Contact :");

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel33.setText("Note About Child :");

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel34.setText("Registration Date :");

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel35.setText("Date Received :");

        lbNextOfKinContact.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNextOfKinContact.setForeground(new java.awt.Color(51, 0, 0));

        lbNoteAboutChild.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNoteAboutChild.setForeground(new java.awt.Color(51, 0, 0));

        lbRegistrationDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbRegistrationDate.setForeground(new java.awt.Color(51, 0, 0));

        lbDateReceived.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDateReceived.setForeground(new java.awt.Color(51, 0, 0));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel35)
                    .addComponent(jLabel33)
                    .addComponent(jLabel32)
                    .addComponent(jLabel34))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNextOfKinContact)
                    .addComponent(lbNoteAboutChild)
                    .addComponent(lbRegistrationDate)
                    .addComponent(lbDateReceived))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(lbNextOfKinContact))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(lbNoteAboutChild))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(lbRegistrationDate))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(lbDateReceived))
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("History disease"));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel29.setText("Doctor Name :");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel30.setText("Past Illness :");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel31.setText("Current Medication :");

        lbCurrentMedication.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCurrentMedication.setForeground(new java.awt.Color(51, 0, 0));

        lbPasIllness.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbPasIllness.setForeground(new java.awt.Color(51, 0, 0));

        lbDocterName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDocterName.setForeground(new java.awt.Color(51, 0, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCurrentMedication)
                    .addComponent(lbPasIllness)
                    .addComponent(lbDocterName))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(lbCurrentMedication))
                .addGap(29, 29, 29)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(lbPasIllness))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(lbDocterName))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout plTableLayout = new javax.swing.GroupLayout(plTable);
        plTable.setLayout(plTableLayout);
        plTableLayout.setHorizontalGroup(
            plTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        plTableLayout.setVerticalGroup(
            plTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(plTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cross.png"))); // NOI18N
        btClose.setText("Close");
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btClose)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(plTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btCloseActionPerformed

    /**
    * @param args the command line arguments
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbAgeGroup;
    private javax.swing.JLabel lbBirthday;
    private javax.swing.JLabel lbCurrentMedication;
    private javax.swing.JLabel lbDateReceived;
    private javax.swing.JLabel lbDocterName;
    private javax.swing.JLabel lbFName;
    private javax.swing.JLabel lbLName;
    private javax.swing.JLabel lbNextOfKinContact;
    private javax.swing.JLabel lbNoteAboutChild;
    private javax.swing.JLabel lbPEmail;
    private javax.swing.JLabel lbPName;
    private javax.swing.JLabel lbPPhone;
    private javax.swing.JLabel lbPWorkNumber;
    private javax.swing.JLabel lbPasIllness;
    private javax.swing.JLabel lbRegistrationDate;
    private javax.swing.JLabel lbSex;
    private javax.swing.JPanel plTable;
    // End of variables declaration//GEN-END:variables

    private void setText(){
        nannybl = new NannyBL();
        rs = nannybl.getResult("spSearchChilCodetbl_Child", ChildCode);
        try {
            if (rs.next()) {
                lbFName.setText(rs.getString("FirstName"));
                lbLName.setText(rs.getString("LastName"));
                if(rs.getInt("Sex") == 1){
                    lbSex.setText("Male");
                }else{
                    lbSex.setText("Female");
                }
                lbAgeGroup.setText(rs.getString("GroupAgeCode"));
                lbAddress.setText(rs.getString("Address"));
                lbBirthday.setText(rs.getString("DateOfBirth"));
                lbPName.setText(rs.getString("ParentName"));
                lbPWorkNumber.setText(rs.getString("ParentWorkNumber"));
                lbPPhone.setText(rs.getString("ParentMobileNumber"));
                lbPEmail.setText(rs.getString("ParentEmailAddress"));
                lbCurrentMedication.setText(rs.getString("CurrentMedication"));
                lbPasIllness.setText(rs.getString("PassIllness"));
                lbDocterName.setText(rs.getString("DoctorName"));
                lbNextOfKinContact.setText(rs.getString("NextOfKinContact"));
                lbNoteAboutChild.setText(rs.getString("NoteAboutChild"));
                lbRegistrationDate.setText(rs.getString("RegistrationDate"));
                lbDateReceived.setText(rs.getString("DateReceived"));
            }else{
                JOptionPane.showMessageDialog(this, "Not find the Children!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmViewChild.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
